import { Inter } from 'next/font/google'
import './styles/main.css'
import Footer from './components/Footer'
import Navbar from './components/Navbar'
import Header from './components/Header'
import Hero from './components/Hero'
import Drawer from './components/Drawer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <Navbar />
        <Drawer />
        <Hero />
        {children}
        <Footer />
      </body>
    </html>
  )
}
